"""
HTML Preview - Generate HTML preview of draft threads
"""

from pathlib import Path
from typing import Dict, Any, List
from datetime import datetime


class HTMLPreview:
    """
    Generates HTML previews of draft threads for visual review
    Creates Twitter-like interface for better visualization
    """
    
    def __init__(self, config: Dict[str, Any] = None):
        """Initialize HTML preview generator"""
        self.config = config or {}
        self.output_dir = Path("bots/previews")
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_preview(self, draft: Dict[str, Any]) -> Path:
        """
        Generate HTML preview for a draft thread
        
        Args:
            draft: Draft data with posts
            
        Returns:
            Path to generated HTML file
        """
        html_content = self._generate_html(draft)
        
        # Save to file
        filename = f"preview_{draft.get('draft_id', 'unknown')[:8]}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        output_path = self.output_dir / filename
        
        with open(output_path, 'w') as f:
            f.write(html_content)
        
        return output_path
    
    def _generate_html(self, draft: Dict[str, Any]) -> str:
        """Generate the HTML content"""
        posts_html = self._generate_posts_html(draft.get('posts', []))
        validation_html = self._generate_validation_html(draft.get('validation', {}))
        style_html = self._generate_style_html(draft.get('style_score', 0))
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Regen Daily - Draft Preview</title>
    <style>
        {self._get_css()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🌱 Regen Daily - Draft Preview</h1>
            <div class="meta">
                <span>Draft ID: {draft.get('draft_id', 'unknown')[:8]}</span>
                <span>Date: {draft.get('thread_date', 'N/A')}</span>
                <span>Status: <span class="status-{draft.get('status', 'draft')}">{draft.get('status', 'draft').upper()}</span></span>
            </div>
        </header>
        
        <main>
            <section class="thread">
                <h2>Thread Posts</h2>
                {posts_html}
            </section>
            
            <aside class="sidebar">
                <div class="validation">
                    <h3>🔍 Link Validation</h3>
                    {validation_html}
                </div>
                
                <div class="style">
                    <h3>✨ Style Score</h3>
                    {style_html}
                </div>
            </aside>
        </main>
        
        <footer>
            <p>Generated by X Bot Draft Generator | Milestone B: Information Pipelines</p>
        </footer>
    </div>
</body>
</html>"""
        
        return html
    
    def _generate_posts_html(self, posts: List[Dict[str, Any]]) -> str:
        """Generate HTML for thread posts"""
        posts_html = []
        
        for i, post in enumerate(posts, 1):
            char_count = post.get('char_count', len(post.get('content', '')))
            char_class = 'good' if char_count <= 280 else 'bad'
            
            urls_html = ""
            if post.get('urls'):
                urls_html = '<div class="urls">' + ''.join(
                    f'<a href="{url}" target="_blank">🔗 {url[:30]}...</a>'
                    for url in post['urls']
                ) + '</div>'
            
            post_html = f"""
            <div class="tweet">
                <div class="tweet-header">
                    <img src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='48' height='48'%3E%3Ccircle cx='24' cy='24' r='24' fill='%234CAF50'/%3E%3Ctext x='24' y='32' text-anchor='middle' fill='white' font-size='24'%3E🌱%3C/text%3E%3C/svg%3E" alt="Regen Network">
                    <div class="tweet-meta">
                        <strong>Regen Network</strong>
                        <span>@regen_network · {i}/{len(posts)}</span>
                    </div>
                </div>
                <div class="tweet-content">
                    {post.get('content', '').replace('\n', '<br>')}
                </div>
                {urls_html}
                <div class="tweet-footer">
                    <span class="char-count {char_class}">{char_count}/280</span>
                    <span class="post-type">{post.get('type', 'content')}</span>
                </div>
            </div>
            """
            posts_html.append(post_html)
        
        return '\n'.join(posts_html)
    
    def _generate_validation_html(self, validation: Dict[str, Any]) -> str:
        """Generate HTML for validation results"""
        if not validation or not validation.get('validated'):
            return '<p class="warning">Links not validated</p>'
        
        total = validation.get('total_links', 0)
        valid = validation.get('valid_links', 0)
        invalid = validation.get('invalid_links', 0)
        
        percentage = (valid / total * 100) if total > 0 else 0
        
        invalid_list = ""
        if validation.get('invalid_urls'):
            invalid_list = '<ul class="invalid-urls">' + ''.join(
                f'<li>❌ {url}</li>' for url in validation['invalid_urls']
            ) + '</ul>'
        
        return f"""
        <div class="validation-stats">
            <div class="stat">
                <span>Total:</span> <strong>{total}</strong>
            </div>
            <div class="stat">
                <span>Valid:</span> <strong class="good">{valid}</strong>
            </div>
            <div class="stat">
                <span>Invalid:</span> <strong class="bad">{invalid}</strong>
            </div>
        </div>
        <div class="progress-bar">
            <div class="progress-fill" style="width: {percentage}%"></div>
        </div>
        {invalid_list}
        """
    
    def _generate_style_html(self, score: float) -> str:
        """Generate HTML for style score"""
        percentage = score * 100
        
        if score >= 0.9:
            status = "Excellent"
            color = "#4CAF50"
        elif score >= 0.7:
            status = "Good"
            color = "#FFC107"
        elif score >= 0.5:
            status = "Needs Improvement"
            color = "#FF9800"
        else:
            status = "Poor"
            color = "#F44336"
        
        return f"""
        <div class="style-score">
            <div class="score-circle" style="background: conic-gradient({color} {percentage * 3.6}deg, #eee 0deg);">
                <span>{percentage:.0f}%</span>
            </div>
            <p class="score-status">{status}</p>
        </div>
        <div class="style-checks">
            <p>✓ Professional tone</p>
            <p>✓ No speculation</p>
            <p>✓ Clear CTAs</p>
            <p>✓ Consistent voice</p>
        </div>
        """
    
    def _get_css(self) -> str:
        """Get CSS styles for the preview"""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background: #f0f2f5;
            color: #14171a;
            line-height: 1.5;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }
        
        header {
            background: white;
            padding: 20px;
            border-radius: 12px;
            margin-bottom: 20px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }
        
        header h1 {
            color: #4CAF50;
            margin-bottom: 10px;
        }
        
        .meta {
            display: flex;
            gap: 20px;
            color: #657786;
            font-size: 14px;
        }
        
        .status-draft { color: #1DA1F2; }
        .status-approved { color: #4CAF50; }
        .status-rejected { color: #F44336; }
        .status-published { color: #9C27B0; }
        
        main {
            display: grid;
            grid-template-columns: 2fr 1fr;
            gap: 20px;
        }
        
        .thread {
            background: white;
            padding: 20px;
            border-radius: 12px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }
        
        .tweet {
            border-bottom: 1px solid #e1e8ed;
            padding: 20px 0;
        }
        
        .tweet:last-child {
            border-bottom: none;
        }
        
        .tweet-header {
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }
        
        .tweet-header img {
            width: 48px;
            height: 48px;
            border-radius: 50%;
            margin-right: 10px;
        }
        
        .tweet-meta {
            display: flex;
            flex-direction: column;
        }
        
        .tweet-meta span {
            color: #657786;
            font-size: 14px;
        }
        
        .tweet-content {
            margin: 10px 0;
            font-size: 16px;
            line-height: 1.5;
        }
        
        .urls {
            margin: 10px 0;
        }
        
        .urls a {
            display: block;
            color: #1DA1F2;
            text-decoration: none;
            margin: 5px 0;
        }
        
        .tweet-footer {
            display: flex;
            justify-content: space-between;
            margin-top: 10px;
            font-size: 14px;
            color: #657786;
        }
        
        .char-count.good { color: #4CAF50; }
        .char-count.bad { color: #F44336; }
        
        .sidebar > div {
            background: white;
            padding: 20px;
            border-radius: 12px;
            margin-bottom: 20px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }
        
        .sidebar h3 {
            margin-bottom: 15px;
            color: #14171a;
        }
        
        .validation-stats {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 10px;
            margin-bottom: 15px;
        }
        
        .stat {
            text-align: center;
        }
        
        .stat span {
            display: block;
            color: #657786;
            font-size: 12px;
        }
        
        .stat strong {
            font-size: 20px;
        }
        
        .good { color: #4CAF50; }
        .bad { color: #F44336; }
        
        .progress-bar {
            height: 8px;
            background: #e1e8ed;
            border-radius: 4px;
            overflow: hidden;
        }
        
        .progress-fill {
            height: 100%;
            background: #4CAF50;
        }
        
        .invalid-urls {
            margin-top: 15px;
            list-style: none;
            font-size: 14px;
        }
        
        .invalid-urls li {
            margin: 5px 0;
            color: #F44336;
        }
        
        .style-score {
            text-align: center;
            margin-bottom: 20px;
        }
        
        .score-circle {
            width: 120px;
            height: 120px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 0 auto 10px;
            position: relative;
        }
        
        .score-circle span {
            font-size: 32px;
            font-weight: bold;
            z-index: 1;
            background: white;
            width: 100px;
            height: 100px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        
        .score-status {
            font-weight: bold;
            margin-bottom: 15px;
        }
        
        .style-checks p {
            margin: 5px 0;
            color: #4CAF50;
            font-size: 14px;
        }
        
        footer {
            text-align: center;
            margin-top: 40px;
            color: #657786;
            font-size: 14px;
        }
        
        .warning {
            color: #FF9800;
            font-style: italic;
        }
        
        @media (max-width: 768px) {
            main {
                grid-template-columns: 1fr;
            }
        }
        """