#!/bin/bash
echo '===================================='
echo 'NOTION CRAWL MONITOR'
echo '===================================='
echo "Time: $(date)"
echo ''
echo 'PROCESS STATUS:'
ps aux | grep python | grep crawl | grep -v grep | wc -l | xargs -I {} echo 'Active crawl processes: {}'
echo ''
echo 'EXTRACTION PROGRESS:'
find notion_crawl/pages -name '*.md' 2>/dev/null | wc -l | xargs -I {} echo 'Pages extracted: {}/729'
find notion_crawl/databases -type d -mindepth 1 2>/dev/null | wc -l | xargs -I {} echo 'Databases extracted: {}/17'
echo ''
echo 'LATEST ACTIVITY:'
tail -3 crawl_output.log 2>/dev/null || echo 'No log file found'
echo ''
echo 'DISK USAGE:'
du -sh notion_crawl 2>/dev/null | xargs -I {} echo 'Total data size: {}'
echo '===================================='
